# Generated by Django 4.1.1 on 2022-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        default=0,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Female", "FEMALE"), ("Male", "Male")], max_length=10
                    ),
                ),
                ("DOB", models.DateField()),
                ("phone_no", models.IntegerField()),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("Kakamega", "KAKAMEGA"),
                            ("Uasin Gishu", "UASIN GISHU"),
                            ("Bungoma", "BUNGOMA"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sub_county",
                    models.CharField(
                        choices=[
                            ("Ikolomani", "IKOLOMANI"),
                            ("Lurambi", "LURAMBI"),
                            ("Wareng", "WARENG"),
                            ("Kapsaret", "KAPSARET"),
                            ("Kimilili", "KIMILILI"),
                            ("Naitiri", "NAITIRI"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "date_created_client",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "KMFL_code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("facility_name", models.CharField(max_length=100)),
                (
                    "facility_county",
                    models.CharField(
                        choices=[
                            ("Kakamega", "KAKAMEGA"),
                            ("Uasin Gishu", "UASIN GISHU"),
                            ("Bungoma", "BUNGOMA"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "facility_subcounty",
                    models.CharField(
                        choices=[
                            ("Ikolomani", "IKOLOMANI"),
                            ("Lurambi", "LURAMBI"),
                            ("Wareng", "WARENG"),
                            ("Kapsaret", "KAPSARET"),
                            ("Kimilili", "KIMILILI"),
                            ("Naitiri", "NAITIRI"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("Dispensary", "DISPENSARY"),
                            ("Hospital", "HOSPITAL"),
                            ("Nursing Home", "NURSING HOME"),
                            ("Health Centre", "HEALTH CENTRE"),
                            ("Dental Clinic", "DENTAL CLINIC"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "facility_owner",
                    models.CharField(
                        choices=[
                            ("MOH", "MINISTRY OF HEALTH"),
                            ("NGO", "NGO"),
                            ("Kenya Police", "KENYA POLICE"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "date_created_facility",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
    ]
